name: Run Tests

on:
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu

        steps:
        - name: Install dependencies
          run: |
            apt install npm
            npm install

        - name: Run tests
          run: |
            npm run test:jest:watch
